version: '3.3'

services:
  db:
    container_name: pg
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: stock_data
    network_mode: host
    # ports:
    #   - "5432:5432" 

  base_populator:
    build: ../
    # ports:
    #   - "8000:8000"
    logging:
      driver: none
    network_mode: host
    command:       
      - /bin/sh
      - -c
      - |
        ls
        set -x
        python3 create_database.py
        python3 populate_database.py

  webserver:
    build: .
    network_mode: host
    command: python3 dashboard.py