version: '3.3'

services:
  db:
    container_name: pg
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: stock_data
    ports:
      - "5433:5432" 

  webserver:
    build: .
    ports:
      - "8000:8000"
    command: python3 dashboard.py